name: Manage S3 Bucket for PRs

on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  create-s3-bucket:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install env0 CLI
        run: |
          npm install -g env0-cli
          env0 login --token ${{ secrets.ENV0_API_TOKEN }}

      - name: Set Bucket Name
        id: set-bucket-name
        run: echo "BUCKET_NAME=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Apply env0 Template to Create S3 Bucket
        run: |
          curl -o env0-template.json https://raw.githubusercontent.com/your-username/your-repo/main/path/to/env0-template.json
          env0 apply -t env0-template.json -p BUCKET_NAME=$BUCKET_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  delete-s3-bucket:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Bucket Name
        id: set-bucket-name
        run: echo "BUCKET_NAME=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Destroy S3 Bucket using env0
        run: |
          env0 destroy -t env0-template.json -p BUCKET_NAME=$BUCKET_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
